// <auto-generated />
using System;
using ApiWebGremioVersion2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiWebGremioVersion2.Migrations
{
    [DbContext(typeof(GremioBDContext))]
    partial class GremioBDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Agremiación", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("estadoOdontologo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("fechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("idOdontologo")
                        .HasColumnType("int");

                    b.Property<int>("nroMatricula")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idOdontologo");

                    b.HasIndex("nroMatricula")
                        .IsUnique();

                    b.ToTable("Agremiación", (string)null);
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Consultorio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("idLocalidad")
                        .HasColumnType("int");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("idLocalidad");

                    b.ToTable("Consultorio", (string)null);
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.ConsultorioOdontologo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("idConsultorio")
                        .HasColumnType("int");

                    b.Property<int>("idOdontologo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("idConsultorio");

                    b.HasIndex("idOdontologo");

                    b.ToTable("ConsultorioOdontologo", (string)null);
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Cuota", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("estadoCouta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idAgremiacion")
                        .HasColumnType("int");

                    b.Property<double>("monto")
                        .HasColumnType("float");

                    b.Property<DateTime>("periodo")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("idAgremiacion");

                    b.ToTable("Cuota", (string)null);
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Localidad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("codigoPostal")
                        .HasColumnType("int");

                    b.Property<int>("idProvincia")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("idProvincia");

                    b.ToTable("Localidad", (string)null);
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.MontoAnual", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("año")
                        .HasColumnType("int");

                    b.Property<double>("monto")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("MontoAnual");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Odontologo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("dni")
                        .IsUnique();

                    b.ToTable("Odontologo", (string)null);
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Provincia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Agremiación", b =>
                {
                    b.HasOne("ApiWebGremioVersion2.Data.Odontologo", "Odontologo")
                        .WithMany("Agremiaciones")
                        .HasForeignKey("idOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odontologo");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Consultorio", b =>
                {
                    b.HasOne("ApiWebGremioVersion2.Data.Localidad", "Localidad")
                        .WithMany("consultorios")
                        .HasForeignKey("idLocalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.ConsultorioOdontologo", b =>
                {
                    b.HasOne("ApiWebGremioVersion2.Data.Consultorio", "Consultorio")
                        .WithMany("Odontologos")
                        .HasForeignKey("idConsultorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiWebGremioVersion2.Data.Odontologo", "Odontologo")
                        .WithMany("Consultorios")
                        .HasForeignKey("idOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Odontologo");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Cuota", b =>
                {
                    b.HasOne("ApiWebGremioVersion2.Data.Agremiación", "Agremiación")
                        .WithMany("Cuotas")
                        .HasForeignKey("idAgremiacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agremiación");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Localidad", b =>
                {
                    b.HasOne("ApiWebGremioVersion2.Data.Provincia", "Provincia")
                        .WithMany("Localidades")
                        .HasForeignKey("idProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Agremiación", b =>
                {
                    b.Navigation("Cuotas");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Consultorio", b =>
                {
                    b.Navigation("Odontologos");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Localidad", b =>
                {
                    b.Navigation("consultorios");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Odontologo", b =>
                {
                    b.Navigation("Agremiaciones");

                    b.Navigation("Consultorios");
                });

            modelBuilder.Entity("ApiWebGremioVersion2.Data.Provincia", b =>
                {
                    b.Navigation("Localidades");
                });
#pragma warning restore 612, 618
        }
    }
}
